// This entire file follows this guide: https://www.devdungeon.com/content/working-files-go

package main

import "time"

func main() {
	//? Timeouts are for me to be able to read the out put of one method before the other,
	//? tho it isn't really necessary

	CreateFile()
	print("\n")
	time.Sleep(time.Second)
	TruncateFile()
	print("\n")
	time.Sleep(time.Second)
	GetFileInfo()
	print("\n")
	time.Sleep(time.Second)
	RenameFile()
	print("\n")
	time.Sleep(time.Second)
	DeleteFile()
	print("\n")
	time.Sleep(time.Second)
	ReadWriteFile()
	print("\n")
	time.Sleep(time.Second)
	ChangePermissions()
	print("\n")
	time.Sleep(time.Second)
	HardLinkFiles()
	print("\n")
	time.Sleep(time.Second)
	SymLinkFiles()
	print("\n")
	time.Sleep(time.Second)
	CopyFile();
	print("\n")
	time.Sleep(time.Second)
	SeekPositionInFile()
	print("\n")
	time.Sleep(time.Second)
	WriteBytesToFile()
	print("\n")
	time.Sleep(time.Second)
	QuickWriteToFile()
	print("\n")
	time.Sleep(time.Second)
	BufferedWriter()
	print("\n")
	time.Sleep(time.Second)
	ReadUpNBytes()
	print("\n")
	time.Sleep(time.Second)
	ReadExactlyNBytes()
	print("\n")
	time.Sleep(time.Second)
	ReadAtLeastNBytes()
	print("\n")
	time.Sleep(time.Second)
	ReadAllBytesOfFile()
	print("\n")
	time.Sleep(time.Second)
	QuickReadFileIntoMemory()
	print("\n")
	time.Sleep(time.Second)
	BufferedReader()
	print("\n")
	time.Sleep(time.Second)
	ReadWithScanner()
	print("\n")
	time.Sleep(time.Second)
	ArchiveFiles()
	print("\n")
	time.Sleep(time.Second)
	ExtractArchivedFiles()
	print("\n")
	time.Sleep(time.Second)
	CompressFile()
	print("\n")
	time.Sleep(time.Second)
	UncompressFile()
	print("\n")
	time.Sleep(time.Second)
	TemporaryFilesAndDirectories()
	print("\n")
	time.Sleep(time.Second)
	DownloadFileOverHttp()
	print("\n")
	time.Sleep(time.Second)
	HashingFile()
	print("\n")
	time.Sleep(time.Second)
	ChecksumFiles()

}
